workflows:
  react-native:
    name: React Native Workflow
    max_build_duration: 60
    environment:
      node: latest
      cocoapods: default
      xcode: latest
      java: latest
      # Removed the entire android section
    scripts:
      - name: Clear Yarn cache
        script: yarn cache clean
      - name: Install dependencies
        script: yarn install --verbose
      - name: Run Android build
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/apk/release/*.apk
