workflows:
  react-native:
    name: React Native Workflow
    max_build_duration: 60
    environment:
      node: latest
      cocoapods: default
      xcode: latest
      java: latest
      # Removed the android section as it contains extra fields
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Run Android build
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/apk/release/*.apk
